<?php

/**
 * Implements hook_feeds_plugins().
 */
function islandora_feeds_feeds_plugins() {
  $info = array();
  $info['IslandoraFeedsOAIProcessor'] = array(
    'name' => 'Islandora OAI Processor',
    'description' => 'Processes OAI-DC to create Fedora objects',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'IslandoraFeedsOAIProcessor',
      'file' => 'IslandoraFeedsOAIProcessor.inc',
      'path' => drupal_get_path('module','islandora_feeds') .'/plugins',
    ),
  );
  $info['IslandoraFeedsZoteroXMLParser'] = array(
    'name' => 'Islandora Zotero-XML Parser',
    'description' => 'Creates XML from Zotero entries',
    'handler' => array(
      'parent' => 'FeedsZoteroParser',
      'class' => 'IslandoraFeedsZoteroXMLParser',
      'file' => 'IslandoraFeedsZoteroXMLParser.inc',
      'path' => drupal_get_path('module','islandora_feeds') .'/plugins',      
    ),
  );
  $info['IslandoraFeedsZoteroProcessor'] = array(
    'name' => 'Islandora Zotero Processor',
    'description' => 'Processes Zotero entries to create Fedora objects',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'IslandoraFeedsZoteroProcessor',
      'file' => 'IslandoraFeedsZoteroProcessor.inc',
      'path' => drupal_get_path('module','islandora_feeds') .'/plugins',
    ),
  );
  return $info;
}

function configDefaults() {
  return array(
    'namespace' => 'article',
    'collection_pid' => 'islandora:articleCollection',
    'content_model' => 'islandora:articleCModel',
  );
}